// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/fi-ts/s3-go/pkg/apis/v1"
)

// S3PartitionServiceClient is an autogenerated mock type for the S3PartitionServiceClient type
type S3PartitionServiceClient struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *S3PartitionServiceClient) List(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.S3PartitionListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.S3PartitionListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Empty, ...grpc.CallOption) (*v1.S3PartitionListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Empty, ...grpc.CallOption) *v1.S3PartitionListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3PartitionListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewS3PartitionServiceClient creates a new instance of S3PartitionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3PartitionServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3PartitionServiceClient {
	mock := &S3PartitionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
