// Code generated by mockery v2.21.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/fi-ts/s3-go/pkg/apis/v1"
)

// S3UserServiceClient is an autogenerated mock type for the S3UserServiceClient type
type S3UserServiceClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *S3UserServiceClient) Create(ctx context.Context, in *v1.S3UserCreateRequest, opts ...grpc.CallOption) (*v1.S3UserWithCredentials, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3UserWithCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserCreateRequest, ...grpc.CallOption) (*v1.S3UserWithCredentials, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserCreateRequest, ...grpc.CallOption) *v1.S3UserWithCredentials); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UserWithCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UserCreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *S3UserServiceClient) Delete(ctx context.Context, in *v1.S3UserDeleteRequest, opts ...grpc.CallOption) (*v1.S3User, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserDeleteRequest, ...grpc.CallOption) (*v1.S3User, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserDeleteRequest, ...grpc.CallOption) *v1.S3User); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UserDeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *S3UserServiceClient) Get(ctx context.Context, in *v1.S3UserDescribeRequest, opts ...grpc.CallOption) (*v1.S3UserWithCredentials, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3UserWithCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserDescribeRequest, ...grpc.CallOption) (*v1.S3UserWithCredentials, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserDescribeRequest, ...grpc.CallOption) *v1.S3UserWithCredentials); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UserWithCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UserDescribeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, in, opts
func (_m *S3UserServiceClient) List(ctx context.Context, in *v1.S3UserListRequest, opts ...grpc.CallOption) (*v1.S3UserList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3UserList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserListRequest, ...grpc.CallOption) (*v1.S3UserList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserListRequest, ...grpc.CallOption) *v1.S3UserList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UserList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UserListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, in, opts
func (_m *S3UserServiceClient) Update(ctx context.Context, in *v1.S3UserUpdateRequest, opts ...grpc.CallOption) (*v1.S3UserWithCredentials, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3UserWithCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserUpdateRequest, ...grpc.CallOption) (*v1.S3UserWithCredentials, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UserUpdateRequest, ...grpc.CallOption) *v1.S3UserWithCredentials); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UserWithCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UserUpdateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewS3UserServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewS3UserServiceClient creates a new instance of S3UserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewS3UserServiceClient(t mockConstructorTestingTNewS3UserServiceClient) *S3UserServiceClient {
	mock := &S3UserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
