// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeS3UserServiceServer is an autogenerated mock type for the UnsafeS3UserServiceServer type
type UnsafeS3UserServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedS3UserServiceServer provides a mock function with given fields:
func (_m *UnsafeS3UserServiceServer) mustEmbedUnimplementedS3UserServiceServer() {
	_m.Called()
}

type NewUnsafeS3UserServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeS3UserServiceServer creates a new instance of UnsafeS3UserServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeS3UserServiceServer(t NewUnsafeS3UserServiceServerT) *UnsafeS3UserServiceServer {
	mock := &UnsafeS3UserServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
