// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: metalstack/io/s3/api/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metalstack_io_s3_api_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_s3_api_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_metalstack_io_s3_api_v1_common_proto_rawDescGZIP(), []int{0}
}

type S3UserKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKey string `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey string `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *S3UserKey) Reset() {
	*x = S3UserKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metalstack_io_s3_api_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3UserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3UserKey) ProtoMessage() {}

func (x *S3UserKey) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_io_s3_api_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3UserKey.ProtoReflect.Descriptor instead.
func (*S3UserKey) Descriptor() ([]byte, []int) {
	return file_metalstack_io_s3_api_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *S3UserKey) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3UserKey) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

var File_metalstack_io_s3_api_v1_common_proto protoreflect.FileDescriptor

var file_metalstack_io_s3_api_v1_common_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x69, 0x6f, 0x2f,
	0x73, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x2e, 0x69, 0x6f, 0x2e, 0x73, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x49, 0x0a, 0x09, 0x53, 0x33, 0x55, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metalstack_io_s3_api_v1_common_proto_rawDescOnce sync.Once
	file_metalstack_io_s3_api_v1_common_proto_rawDescData = file_metalstack_io_s3_api_v1_common_proto_rawDesc
)

func file_metalstack_io_s3_api_v1_common_proto_rawDescGZIP() []byte {
	file_metalstack_io_s3_api_v1_common_proto_rawDescOnce.Do(func() {
		file_metalstack_io_s3_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_metalstack_io_s3_api_v1_common_proto_rawDescData)
	})
	return file_metalstack_io_s3_api_v1_common_proto_rawDescData
}

var file_metalstack_io_s3_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metalstack_io_s3_api_v1_common_proto_goTypes = []any{
	(*Empty)(nil),     // 0: metalstack.io.s3.api.v1.Empty
	(*S3UserKey)(nil), // 1: metalstack.io.s3.api.v1.S3UserKey
}
var file_metalstack_io_s3_api_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metalstack_io_s3_api_v1_common_proto_init() }
func file_metalstack_io_s3_api_v1_common_proto_init() {
	if File_metalstack_io_s3_api_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metalstack_io_s3_api_v1_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metalstack_io_s3_api_v1_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*S3UserKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metalstack_io_s3_api_v1_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metalstack_io_s3_api_v1_common_proto_goTypes,
		DependencyIndexes: file_metalstack_io_s3_api_v1_common_proto_depIdxs,
		MessageInfos:      file_metalstack_io_s3_api_v1_common_proto_msgTypes,
	}.Build()
	File_metalstack_io_s3_api_v1_common_proto = out.File
	file_metalstack_io_s3_api_v1_common_proto_rawDesc = nil
	file_metalstack_io_s3_api_v1_common_proto_goTypes = nil
	file_metalstack_io_s3_api_v1_common_proto_depIdxs = nil
}
